#!/usr/bin/env bash
# phase2/03-openwebui.sh — Section 17 Phase 2 step 3: Open WebUI 0.11.4 with the offline hardening of Section 12.1
# and Appendix B; A.T.L.A.S., Ren and Arthur registered as models; the router Filter installed; the D9 retention
# contract; V12. Sourced by phase2-services.sh through run_phase_steps; defines step_03 only.
#
# Order (each part idempotent):
#   1. Secrets: $ATLAS_ETC/secrets/openwebui.env (WEBUI_SECRET_KEY so the JWT secret survives a rebuild, research 1.1;
#      OPENAI_API_KEY=atlas-local, the dummy the orchestrator ignores) and openwebui-principal.env (the first admin's
#      email and password, generated once, root 600, never printed: the step tells the Principal where to read it).
#   2. `core_compose up -d open-webui` from docker/core/compose.yml (host network; every offline variable the
#      services research verified is in that file; capabilities dropped, pid and memory ceilings), then the permanent
#      egress fence (below) BEFORE waiting for /health, so no start-up path runs unfenced longer than the pull takes.
#   3. First admin created NON-INTERACTIVELY: POST /api/v1/auths/signup works while the user table is empty even with
#      ENABLE_SIGNUP=false (research 1.4 VERIFIED); re-runs sign in instead. An admin API key (ENABLE_API_KEYS=true) is
#      stored for the retention task; the JWT is the fallback if the key route differs (UNVERIFIED response shape).
#      Credentials never sit on a command line (/proc/<pid>/cmdline is world-readable): curl takes the bearer header
#      from a process substitution (-H @/dev/fd/N) and JSON bodies on stdin; python builds bodies from the environment.
#      Nothing of a credential-issuing response is ever logged except its key names.
#   4. Models: the orchestrator's /v1/models (atlas, ren, arthur) must appear in Open WebUI's model list.
#   5. Filter: orchestrator/src/atlas/openwebui_filter.py installed through POST /api/v1/functions/create (or
#      .../update), valve ORCHESTRATOR_URL set, toggled active and global (toggles are flips: state is read first).
#   6. Retention (D9, 90 days): the orchestrator's Celery task; this step proves the contract statically (task
#      registered and scheduled in atlas.celery_app; the task modules are imported the way a worker imports them, since
#      `app.tasks` alone holds only celery.* built-ins) and writes its settings; the run is nightly under beat.
#   7. Short-circuit proof of the update check, then run_verify V12 v12-openwebui-offline.sh (fail recorded, not fatal
#      here: the Phase 2 gate blocks on it).
#
# EGRESS FENCE (fix round; Section 12.1 "the node quietly is not zero-cloud"): Open WebUI is root inside a container on
# the host network. Blanked proxy variables only remove a default; any code path that names a proxy (RAG web loader,
# a malicious document) could reach squid on 127.0.0.1:3128 and through it every allowlisted domain, and every
# unauthenticated loopback service. V12 watches a 120 s window; this step makes V12's rule permanent:
# /usr/local/sbin/atlas-openwebui-egress (written here) keeps an iptables chain ATLAS-OPENWEBUI, jumped to from OUTPUT,
# that DROPs every NEW connection from the container's cgroup (-m cgroup --path, socket owner) that leaves through a
# non-loopback interface, and on loopback every connection to 3128 (squid), 6379 (Redis) and 8000 (ChromaDB). Replies
# to LAN/WireGuard clients are ESTABLISHED and never match. The unit atlas-openwebui-egress.service (written here too)
# re-applies the rules every 10 s (a recreated container has a new cgroup path; a `ufw reload` flushes OUTPUT) and
# the step applies them once immediately after `compose up`. Both files are generated by this step rather than kept in
# systemd/ because CONVENTIONS.md §1 fixes that directory's list; the header of each says so.
#
# PWA (Section 12.1 "installs as an app on phone and laptop"): browsers offer "install" only in a secure context
# (https or localhost). Day 1 serves http://<LAN IP>:$OPENWEBUI_PORT over LAN and WireGuard and provides no TLS, so the
# install-as-app sentence is NOT delivered by this step; browser-tab access is. Recorded in the summary block for the
# Principal to decide (accept browser-tab access, or add a TLS front such as caddy on 443 with a self-signed
# certificate installed on the phone and laptop — a Phase 1 firewall change and a new unit, not made here).
#
# CONTRACTS (CONVENTIONS.md does not state them):
#   * $ATLAS_DAY1_DIR/orchestrator/src/atlas/openwebui_filter.py exists and is a valid Open WebUI Filter: a class named
#     `Filter` (type detection is hasattr(module, "Filter"), research 1.4 VERIFIED) with `Valves.ORCHESTRATOR_URL`
#     (pydantic field) and no `requirements:` frontmatter (pip at load time is impossible offline).
#   * atlas.celery_app registers the chat-retention task and schedules it nightly in beat_schedule (checked below by
#     name: a task or schedule key containing "retention"). The task reads OPENWEBUI_URL, OPENWEBUI_ADMIN_TOKEN_FILE (a
#     bare token on the first line, atlas-readable) and OPENWEBUI_CHAT_RETENTION_DAYS (orchestrator.env, step 02), lists
#     chats with GET /api/v1/chats/all/db, keeps pinned chats and vault-tagged content (10.5), summarises the rest into
#     the Vector Cortex, then DELETE /api/v1/chats/{id} (research 1.6 VERIFIED routes). The SQLite fallback in research
#     1.6 is for a dead API only, container stopped.
#   * core_compose / orch_admin / orch_env_source_cmd come from phase2/02-orchestrator.sh (sourced earlier by
#     run_phase_steps). $ATLAS_ETC/secrets is root:atlas 750 (02's header): atlas must traverse it to read the token.
[[ -n "${ATLAS_DAY1_DIR:-}" ]] || {
  # shellcheck source=lib/common.sh
  source "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")/../lib/common.sh"
}
if ! declare -F core_compose >/dev/null; then
  # shellcheck source=phase2/02-orchestrator.sh
  source "$ATLAS_DAY1_DIR/phase2/02-orchestrator.sh"
fi

OW_SECRETS="$ATLAS_ETC/secrets/openwebui.env"
OW_PRINCIPAL="$ATLAS_ETC/secrets/openwebui-principal.env"
OW_TOKEN_FILE="$ATLAS_ETC/secrets/openwebui-admin.token"
OW_FILTER_SRC="$ATLAS_DAY1_DIR/orchestrator/src/atlas/openwebui_filter.py"
OW_FILTER_ID="atlas_router"
OW_CONTAINER="atlas-openwebui"
OW_EGRESS_BIN=/usr/local/sbin/atlas-openwebui-egress
OW_EGRESS_UNIT=atlas-openwebui-egress.service
OW_URL=""
OW_TOKEN=""

_ow_rand() { head -c 48 /dev/urandom | base64 | tr -dc 'A-Za-z0-9' | head -c "${1:-32}"; }

# _ow_split RESPONSE — sets OW_CODE and OW_BODY from the "<body>\n<code>" curl output.
_ow_split() {
  local raw="$1"
  OW_CODE="${raw##*$'\n'}"
  OW_BODY="${raw%$'\n'*}"
  [[ "$OW_CODE" =~ ^[0-9]{3}$ ]] || { OW_CODE="000"; OW_BODY="$raw"; }
}
OW_CODE=""; OW_BODY=""

# _ow_api METHOD PATH [JSON_BODY] — sets OW_CODE/OW_BODY. The bearer token goes to curl through a process substitution
# (`-H @/dev/fd/N`, curl reads header lines from a file), the body on stdin: neither is ever on argv.
_ow_api() {
  local method="$1" path="$2" body="${3:-}" raw
  if [[ -n "$OW_TOKEN" && -n "$body" ]]; then
    raw="$(curl -s --noproxy '*' --max-time 60 -X "$method" -H @<(printf 'Authorization: Bearer %s\n' "$OW_TOKEN") \
      -H 'Content-Type: application/json' --data-binary @- -w '\n%{http_code}' "$OW_URL$path" <<<"$body" 2>/dev/null || true)"
  elif [[ -n "$OW_TOKEN" ]]; then
    raw="$(curl -s --noproxy '*' --max-time 60 -X "$method" -H @<(printf 'Authorization: Bearer %s\n' "$OW_TOKEN") \
      -w '\n%{http_code}' "$OW_URL$path" 2>/dev/null || true)"
  elif [[ -n "$body" ]]; then
    raw="$(curl -s --noproxy '*' --max-time 60 -X "$method" -H 'Content-Type: application/json' --data-binary @- \
      -w '\n%{http_code}' "$OW_URL$path" <<<"$body" 2>/dev/null || true)"
  else
    raw="$(curl -s --noproxy '*' --max-time 60 -X "$method" -w '\n%{http_code}' "$OW_URL$path" 2>/dev/null || true)"
  fi
  _ow_split "$raw"
}

# _ow_json JSON PYEXPR — evaluate a python expression over the parsed JSON (bound to d); prints the result. The JSON
# travels on stdin (it may hold a token).
_ow_json() {
  python3 -c 'import json, sys
d = json.loads(sys.stdin.read())
print(eval(sys.argv[1]))' "$2" <<<"$1" 2>/dev/null
}

# _ow_keys JSON — the key names of a JSON object, never its values (what a die/warn may show of a credential response).
_ow_keys() {
  _ow_json "$1" 'sorted(d) if isinstance(d, dict) else type(d).__name__' || echo "unparsable (${#1} bytes)"
}

_ow_secrets() {
  ensure_dir "$ATLAS_ETC/secrets" root:atlas 750
  if [[ ! -s "$OW_SECRETS" ]] || ! grep -q '^WEBUI_SECRET_KEY=.\+' "$OW_SECRETS"; then
    {
      echo "# Open WebUI secrets (compose env_file for docker/core/compose.yml; CONVENTIONS.md §2). Generated by Phase 2 step 3."
      echo "WEBUI_SECRET_KEY=$(python3 -c 'import secrets; print(secrets.token_hex(32))')"
      echo "OPENAI_API_KEY=atlas-local"
    } | install -m 600 -o root -g root /dev/stdin "$OW_SECRETS"
    log "generated $OW_SECRETS (WEBUI_SECRET_KEY; root 600)"
  fi
  if [[ ! -s "$OW_PRINCIPAL" ]]; then
    {
      echo "# The Principal's Open WebUI login (first admin). Generated once by Phase 2 step 3; change it in the UI if you like."
      echo "OPENWEBUI_ADMIN_EMAIL=principal@$DOMAIN"
      echo "OPENWEBUI_ADMIN_PASSWORD=$(_ow_rand 24)"
      echo "OPENWEBUI_ADMIN_NAME=Principal"
    } | install -m 600 -o root -g root /dev/stdin "$OW_PRINCIPAL"
    log "generated the Principal's Open WebUI login into $OW_PRINCIPAL (root 600; never printed)"
  fi
}

# --- the permanent egress fence ------------------------------------------------------------------------------------------
_ow_egress_install() {
  command -v iptables >/dev/null || die "iptables is not installed (Phase 1 step 4 installs it); the Open WebUI egress fence cannot be built"
  cat >"$OW_EGRESS_BIN.tmp" <<'FENCE'
#!/usr/bin/env bash
# /usr/local/sbin/atlas-openwebui-egress — written by scripts/day1/phase2/03-openwebui.sh (generated, not a
# repository unit: CONVENTIONS.md §1 fixes the systemd/ list). Permanent runtime fence for the atlas-openwebui
# container (host network; Section 12.1; the rule verify/v12-openwebui-offline.sh proves for 120 s, enforced for ever):
#   * every NEW connection whose socket belongs to the container's cgroup and leaves through a non-loopback interface
#     is logged (rate-limited, prefix "[ATLAS openwebui egress denied]") and DROPPED; replies to LAN/WireGuard clients
#     are ESTABLISHED and never match;
#   * on loopback, connections from that cgroup to tcp 3128 (squid: the way out through the allowlist), 6379 (Redis:
#     the Celery broker) and 8000 (ChromaDB: the Vector Cortex, no auth) are dropped too. The orchestrator (8800), the
#     bge-m3 llama-server, Kokoro, speaches and docling stay reachable.
# Rules live in the chain ATLAS-OPENWEBUI (iptables and ip6tables), jumped to from OUTPUT.
#   apply  [CONTAINER]   rebuild the chain for the container's current cgroup path (no-op while it is not running)
#   watch  [CONTAINER]   apply, then re-check every 10 s and re-apply when the container was recreated or the chain
#                        or the OUTPUT jump disappeared (ufw reload flushes OUTPUT); the unit atlas-openwebui-egress
#                        runs this
#   status [CONTAINER]   print the cgroup path and the chain; exit 1 when the running container is not fenced
# Requires the xt_cgroup v2 path match (`-m cgroup --path`, cgroup2 unified hierarchy: Ubuntu's default). If the
# kernel lacks it, apply FAILS (exit 1) and says so: an unfenced Open WebUI is never reported as fenced.
set -euo pipefail

CHAIN=ATLAS-OPENWEBUI
LOOPBACK_DROP_PORTS=3128,6379,8000

cgroup_path_of() {   # prints the cgroup v2 path (without the leading /) of the running container, or nothing
  local ctr="$1" pid
  pid="$(docker inspect -f '{{.State.Pid}}' "$ctr" 2>/dev/null || echo 0)"
  [[ "$pid" =~ ^[0-9]+$ && "$pid" -gt 0 ]] || return 0
  awk -F: '$1=="0" {print $3; exit}' "/proc/$pid/cgroup" 2>/dev/null | sed 's#^/##'
}

fenced() {   # fenced BIN CGREL -> 0 when the chain carries the DROP for this cgroup and OUTPUT jumps to it
  local bin="$1" cg="$2"
  "$bin" -w -C OUTPUT -j "$CHAIN" 2>/dev/null \
    && "$bin" -w -C "$CHAIN" -m cgroup --path "$cg" ! -o lo -m conntrack --ctstate NEW -j DROP 2>/dev/null
}

build_chain() {   # build_chain BIN CGREL
  local bin="$1" cg="$2"
  "$bin" -w -N "$CHAIN" 2>/dev/null || true
  "$bin" -w -F "$CHAIN"
  "$bin" -w -A "$CHAIN" -m cgroup --path "$cg" ! -o lo -m conntrack --ctstate NEW -m limit --limit 6/min \
    -j LOG --log-prefix "[ATLAS openwebui egress denied] " --log-level 4
  "$bin" -w -A "$CHAIN" -m cgroup --path "$cg" ! -o lo -m conntrack --ctstate NEW -j DROP
  "$bin" -w -A "$CHAIN" -m cgroup --path "$cg" -o lo -p tcp -m multiport --dports "$LOOPBACK_DROP_PORTS" \
    -m conntrack --ctstate NEW -m limit --limit 6/min -j LOG --log-prefix "[ATLAS openwebui egress denied] " --log-level 4
  "$bin" -w -A "$CHAIN" -m cgroup --path "$cg" -o lo -p tcp -m multiport --dports "$LOOPBACK_DROP_PORTS" -j DROP
  "$bin" -w -C OUTPUT -j "$CHAIN" 2>/dev/null || "$bin" -w -I OUTPUT 1 -j "$CHAIN"
}

apply() {
  local ctr="$1" cg bin
  cg="$(cgroup_path_of "$ctr")"
  if [[ -z "$cg" ]]; then
    echo "atlas-openwebui-egress: $ctr is not running; the chain is left as it is"
    return 0
  fi
  for bin in iptables ip6tables; do
    command -v "$bin" >/dev/null || { [[ "$bin" == ip6tables ]] && continue; echo "atlas-openwebui-egress: $bin missing" >&2; return 1; }
    if ! build_chain "$bin" "$cg"; then
      echo "atlas-openwebui-egress: $bin could not build $CHAIN for cgroup $cg (no xt_cgroup --path support? cgroup v2 unified hierarchy required); Open WebUI is NOT fenced" >&2
      return 1
    fi
  done
  echo "atlas-openwebui-egress: $CHAIN applied for $ctr (cgroup $cg): non-loopback NEW dropped, loopback tcp $LOOPBACK_DROP_PORTS dropped"
}

status() {
  local ctr="$1" cg
  cg="$(cgroup_path_of "$ctr")"
  echo "container=$ctr cgroup=${cg:-<not running>}"
  iptables -w -S "$CHAIN" 2>/dev/null || echo "(no $CHAIN chain)"
  [[ -z "$cg" ]] && return 0
  fenced iptables "$cg"
}

watch() {
  local ctr="$1" cg
  apply "$ctr" || true
  while sleep 10; do
    cg="$(cgroup_path_of "$ctr")"
    [[ -n "$cg" ]] || continue
    if ! fenced iptables "$cg"; then
      apply "$ctr" || true
    fi
  done
}

cmd="${1:-}"; ctr="${2:-atlas-openwebui}"
case "$cmd" in
  apply)  apply "$ctr" ;;
  watch)  watch "$ctr" ;;
  status) status "$ctr" ;;
  *) echo "usage: atlas-openwebui-egress apply|watch|status [CONTAINER]" >&2; exit 2 ;;
esac
FENCE
  install -m 755 -o root -g root "$OW_EGRESS_BIN.tmp" "$OW_EGRESS_BIN"
  rm -f "$OW_EGRESS_BIN.tmp"
  bash -n "$OW_EGRESS_BIN" || die "$OW_EGRESS_BIN does not parse"
  cat >"/etc/systemd/system/$OW_EGRESS_UNIT.tmp" <<UNIT
# /etc/systemd/system/$OW_EGRESS_UNIT — written by scripts/day1/phase2/03-openwebui.sh (generated, not a repository
# unit). Keeps the Open WebUI egress fence ($OW_EGRESS_BIN, header there) applied: at boot after docker, and
# whenever the container is recreated or the OUTPUT chain is flushed. Section 12.1; V12 proves the rule, this enforces it.
[Unit]
Description=Egress fence for the $OW_CONTAINER container (Section 12.1, V12 made permanent)
After=docker.service atlas-docker-egress.service
Wants=docker.service

[Service]
Type=simple
ExecStart=$OW_EGRESS_BIN watch $OW_CONTAINER
Restart=always
RestartSec=5

[Install]
WantedBy=multi-user.target
UNIT
  install -m 644 -o root -g root "/etc/systemd/system/$OW_EGRESS_UNIT.tmp" "/etc/systemd/system/$OW_EGRESS_UNIT"
  rm -f "/etc/systemd/system/$OW_EGRESS_UNIT.tmp"
  systemctl daemon-reload
  systemctl enable --quiet "$OW_EGRESS_UNIT"
  systemctl restart "$OW_EGRESS_UNIT" || die "$OW_EGRESS_UNIT failed to start: $(journalctl -u "$OW_EGRESS_UNIT" --no-pager -n 10 2>&1 | tail -n 5)"
}

_ow_egress_apply_now() {
  # Immediate application (the unit's first apply may race the container start); the status check is the proof.
  "$OW_EGRESS_BIN" apply "$OW_CONTAINER" || die "the Open WebUI egress fence could not be applied (message above): refusing to run Open WebUI unfenced (Section 12.1)"
  local st
  st="$("$OW_EGRESS_BIN" status "$OW_CONTAINER" 2>&1)" || die "the Open WebUI egress fence is not in place for the running container: $st"
  log "egress fence in place for $OW_CONTAINER: $(grep -c -- '-j DROP' <<<"$st") DROP rule(s) in ATLAS-OPENWEBUI; $OW_EGRESS_UNIT active"
}

_ow_up() {
  grep -qE '^[[:space:]]+open-webui:' "$ATLAS_DAY1_DIR/docker/core/compose.yml" || die "docker/core/compose.yml defines no 'open-webui' service"
  wait_http "http://127.0.0.1:$ORCH_PORT/health" 30 || die "the orchestrator is not healthy on 127.0.0.1:$ORCH_PORT (step 02 must have run; systemctl status atlas-orchestrator)"
  ensure_dir "$ATLAS_SRV/data/open-webui" root:root 750
  _ow_egress_install
  proxy_env
  log "docker compose up -d open-webui (ghcr.io/open-webui/open-webui:v0.11.4, ~4 GB pull through the proxy on first run)"
  retry 3 core_compose up -d --quiet-pull open-webui \
    || die "docker compose up open-webui failed (ghcr.io and pkg-containers.githubusercontent.com must be allowlisted): $(core_compose logs --tail 20 open-webui 2>&1 | tail -n 20)"
  _ow_egress_apply_now
  OW_URL="http://127.0.0.1:$OPENWEBUI_PORT"
  if ! wait_http "$OW_URL/health" 300; then
    core_compose logs --tail 40 open-webui >&2 || true
    die "Open WebUI did not answer 200 on $OW_URL/health within 300 s (container logs above; if they show a permission or capability error, the cap_add set in docker/core/compose.yml is too narrow for this image)"
  fi
  # Host network: the listener must be the one on $OPENWEBUI_PORT; ufw scopes it to LAN + WireGuard (Phase 1 step 4).
  local mode
  mode="$(docker inspect -f '{{.HostConfig.NetworkMode}}' "$OW_CONTAINER" 2>/dev/null || true)"
  [[ "$mode" == host ]] || die "$OW_CONTAINER runs with NetworkMode=$mode; docker/core/compose.yml expects host (it must reach the loopback-only orchestrator and llama-server)"
  ss -ltnH "sport = :$OPENWEBUI_PORT" | grep -q ":$OPENWEBUI_PORT" || die "nothing listens on TCP $OPENWEBUI_PORT after the container came up"
  local rules
  rules="$(ufw status 2>/dev/null | grep -c "$OPENWEBUI_PORT/tcp" || true)"
  (( rules > 0 )) || warn "ufw shows no rule for $OPENWEBUI_PORT/tcp: Phase 1 step 4 should have allowed it on the LAN interface and the WireGuard bridge (Section 3.6)"
  log "Open WebUI up on $OW_URL (host network; ufw rules for $OPENWEBUI_PORT/tcp: $rules)"
}

_ow_admin_token() {
  local email pass name payload
  email="$(awk -F= '$1=="OPENWEBUI_ADMIN_EMAIL" {print $2; exit}' "$OW_PRINCIPAL")"
  pass="$(awk -F= '$1=="OPENWEBUI_ADMIN_PASSWORD" {print $2; exit}' "$OW_PRINCIPAL")"
  name="$(awk -F= '$1=="OPENWEBUI_ADMIN_NAME" {print $2; exit}' "$OW_PRINCIPAL")"
  [[ -n "$email" && -n "$pass" ]] || die "$OW_PRINCIPAL lacks OPENWEBUI_ADMIN_EMAIL/PASSWORD"
  # Bodies are built from the environment of one python call, never from argv.
  payload="$(OW_E="$email" OW_P="$pass" OW_N="${name:-Principal}" python3 -c 'import json, os
print(json.dumps({"email": os.environ["OW_E"], "password": os.environ["OW_P"], "name": os.environ["OW_N"]}))')"
  # First user == admin, only while the table is empty (research 1.4); otherwise sign in.
  _ow_api POST /api/v1/auths/signup "$payload"
  if [[ "$OW_CODE" == 200 ]]; then
    OW_TOKEN="$(_ow_json "$OW_BODY" 'd["token"]')"
    log "first admin created through /api/v1/auths/signup ($email, role $(_ow_json "$OW_BODY" 'd.get("role")'))"
  else
    payload="$(OW_E="$email" OW_P="$pass" python3 -c 'import json, os
print(json.dumps({"email": os.environ["OW_E"], "password": os.environ["OW_P"]}))')"
    _ow_api POST /api/v1/auths/signin "$payload"
    [[ "$OW_CODE" == 200 ]] || die "Open WebUI signup and signin both failed (signin HTTP $OW_CODE, response keys: $(_ow_keys "$OW_BODY")). If the data dir $ATLAS_SRV/data/open-webui predates $OW_PRINCIPAL, the stored password differs: reset it in the UI or move the data dir away and re-run with --force 03"
    OW_TOKEN="$(_ow_json "$OW_BODY" 'd["token"]')"
    log "signed in as the existing admin $email"
  fi
  [[ -n "$OW_TOKEN" ]] || die "no 'token' in the auth response (keys: $(_ow_keys "$OW_BODY"))"
  local role
  role="$(_ow_json "$OW_BODY" 'd.get("role")')"
  [[ "$role" == admin ]] || die "the account $email has role '$role', not admin: the first user was created by someone else (data dir $ATLAS_SRV/data/open-webui)"

  # Long-lived admin credential for the retention task (atlas reads it). Prefer an API key (ENABLE_API_KEYS=true;
  # UNVERIFIED response shape: {"api_key": "sk-..."}); fall back to the JWT, whose default lifetime in Open WebUI is
  # unlimited (JWT_EXPIRES_IN default -1, UNVERIFIED here), and say so.
  local stored="" kind=""
  _ow_api POST /api/v1/auths/api_key
  if [[ "$OW_CODE" == 200 ]]; then
    stored="$(_ow_json "$OW_BODY" 'd.get("api_key") or ""')"
    kind="api-key"
  fi
  if [[ -z "$stored" ]]; then
    warn "POST /api/v1/auths/api_key gave HTTP $OW_CODE (response keys: $(_ow_keys "$OW_BODY")); storing the admin JWT instead (UNVERIFIED lifetime)"
    stored="$OW_TOKEN"; kind="jwt"
  fi
  printf '%s\n' "$stored" | install -m 600 -o atlas -g atlas /dev/stdin "$OW_TOKEN_FILE"
  # The reader is the chat-retention task (user atlas): prove the read now, not at 04:15 (fix round).
  svc_user_run cat "$OW_TOKEN_FILE" >/dev/null 2>&1 \
    || die "the atlas account cannot read $OW_TOKEN_FILE ($(stat -c '%U:%G %a' "$OW_TOKEN_FILE"); $ATLAS_ETC/secrets is $(stat -c '%U:%G %a' "$ATLAS_ETC/secrets"), must be root:atlas 750): the D9 retention task would fail every night"
  log "admin credential ($kind) written to $OW_TOKEN_FILE (atlas:atlas 600, read-back as atlas ok) for the D9 retention task"
}

_ow_models() {
  # Section 12.1: A.T.L.A.S. as one model, Ren and Arthur as direct models. They are the orchestrator's /v1/models
  # entries; Open WebUI lists them through its OpenAI connection (research 1.3). Path /api/models is the UI's own
  # list (UNVERIFIED path); /openai/models is the VERIFIED proxied list; either proves the registration.
  local path ids="" found=0
  for path in /api/models /openai/models; do
    _ow_api GET "$path"
    [[ "$OW_CODE" == 200 ]] || continue
    ids="$(_ow_json "$OW_BODY" 'sorted({m.get("id") for m in (d.get("data") if isinstance(d, dict) else d) if isinstance(m, dict)})' || true)"
    if python3 -c 'import sys; ids=sys.argv[1]; sys.exit(0 if all(("\x27%s\x27" % m) in ids for m in ("atlas","ren","arthur")) else 1)' "$ids"; then
      found=1
      log "models registered in Open WebUI via $path: $ids"
      break
    fi
    warn "$path lists $ids (atlas/ren/arthur not all present yet)"
  done
  (( found )) || die "Open WebUI does not list the models atlas, ren and arthur (OPENAI_API_BASE_URL=http://127.0.0.1:$ORCH_PORT/v1; check 'docker logs $OW_CONTAINER' for the model-list fetch and the orchestrator's GET /v1/models)"
}

_ow_filter() {
  [[ -f "$OW_FILTER_SRC" ]] || die "contract: $OW_FILTER_SRC does not exist (the orchestrator writer's Open WebUI Filter)"
  grep -qE '^class Filter\b' "$OW_FILTER_SRC" || die "contract: $OW_FILTER_SRC defines no top-level 'class Filter' (Open WebUI detects the type by that name)"
  if grep -qiE '^requirements:' "$OW_FILTER_SRC"; then
    die "contract: $OW_FILTER_SRC carries a 'requirements:' frontmatter line; Open WebUI would pip-install at load time, impossible offline (rule §7.1)"
  fi
  local payload
  payload="$(python3 - "$OW_FILTER_ID" "$OW_FILTER_SRC" <<'PY'
import json, sys
fid, path = sys.argv[1:3]
print(json.dumps({"id": fid, "name": "A.T.L.A.S. Router",
                  "content": open(path, encoding="utf-8").read(),
                  "meta": {"description": "Relays every prompt to the A.T.L.A.S. orchestrator (Section 7.1); the router lives there, this is the thin relay."}}))
PY
)"
  _ow_api GET "/api/v1/functions/id/$OW_FILTER_ID"
  if [[ "$OW_CODE" == 200 ]]; then
    _ow_api POST "/api/v1/functions/id/$OW_FILTER_ID/update" "$payload"
  else
    _ow_api POST /api/v1/functions/create "$payload"
  fi
  [[ "$OW_CODE" == 200 ]] || die "installing the Filter function failed (HTTP $OW_CODE): ${OW_BODY:0:300} — is the file a valid Open WebUI Filter (research 1.4 skeleton)?"
  local ftype
  ftype="$(_ow_json "$OW_BODY" 'd.get("type")')"
  [[ "$ftype" == filter ]] || die "Open WebUI classified $OW_FILTER_SRC as type '$ftype', not 'filter' (class must be named Filter)"

  local valves
  valves="$(python3 -c 'import json, sys; print(json.dumps({"ORCHESTRATOR_URL": sys.argv[1]}))' "http://127.0.0.1:$ORCH_PORT")"
  _ow_api POST "/api/v1/functions/id/$OW_FILTER_ID/valves/update" "$valves"
  [[ "$OW_CODE" == 200 ]] || die "valves/update failed (HTTP $OW_CODE): ${OW_BODY:0:200} — the Filter's Valves must declare ORCHESTRATOR_URL"

  # Toggles flip; read first, flip only when needed, then read back and assert (research 1.4).
  local state flag
  _ow_api GET "/api/v1/functions/id/$OW_FILTER_ID"; state="$OW_BODY"
  for flag in is_active is_global; do
    if [[ "$(_ow_json "$state" "bool(d.get('$flag'))")" != True ]]; then
      if [[ "$flag" == is_active ]]; then _ow_api POST "/api/v1/functions/id/$OW_FILTER_ID/toggle"
      else _ow_api POST "/api/v1/functions/id/$OW_FILTER_ID/toggle/global"; fi
    fi
  done
  _ow_api GET "/api/v1/functions/id/$OW_FILTER_ID"; state="$OW_BODY"
  [[ "$(_ow_json "$state" "bool(d.get('is_active')) and bool(d.get('is_global'))")" == True ]] \
    || die "the Filter is not active+global after toggling: ${state:0:200}"
  log "Filter '$OW_FILTER_ID' installed from $OW_FILTER_SRC: active, global, ORCHESTRATOR_URL=http://127.0.0.1:$ORCH_PORT"
}

_ow_retention_contract() {
  # D9: 90-day retention is the orchestrator's Celery task under beat. Static proof of the contract, no side effects
  # (running it now would need ChromaDB, which step 4 brings up later in Section 17 order). Celery imports the
  # `include=` task modules only in a worker (app.loader.import_default_modules), never on `import atlas.celery_app`,
  # so the registry is filled the same way here before it is inspected (fix round: the check always died before).
  svc_user_run /bin/bash -c "$(orch_env_source_cmd)exec '$ORCH_VENV/bin/python' -c '
import sys
from atlas.celery_app import app
app.loader.import_default_modules()
sched = app.conf.beat_schedule or {}
hit = [k for k, v in sched.items() if \"retention\" in k.lower() or \"retention\" in str(v.get(\"task\", \"\")).lower()]
tasks = [t for t in app.tasks if \"retention\" in t.lower()]
if not hit or not tasks:
    print(\"beat_schedule keys:\", sorted(sched), \"tasks:\", sorted(t for t in app.tasks if not t.startswith(\"celery.\")), file=sys.stderr)
    sys.exit(1)
print(\"retention task\", tasks[0], \"scheduled as\", hit[0], sched[hit[0]].get(\"schedule\"))
'" || die "contract: atlas.celery_app has no chat-retention task in beat_schedule (D9, Section 10.4); see the header of this file"
  ensure_kv "$ORCH_ENV" OPENWEBUI_URL "http://127.0.0.1:$OPENWEBUI_PORT"
  ensure_kv "$ORCH_ENV" OPENWEBUI_ADMIN_TOKEN_FILE "$OW_TOKEN_FILE"
  ensure_kv "$ORCH_ENV" OPENWEBUI_CHAT_RETENTION_DAYS 90
  chown root:atlas "$ORCH_ENV"; chmod 640 "$ORCH_ENV"
  # beat and the workers read orchestrator.env at start: restart so the retention settings are live.
  systemctl restart atlas-celery-beat || warn "atlas-celery-beat did not restart cleanly (journalctl -u atlas-celery-beat)"
  log "D9 retention: nightly Celery task under beat, 90 days, admin credential $OW_TOKEN_FILE"
}

_ow_update_check_shortcircuit() {
  # research 1.5 (VERIFIED source): with OFFLINE_MODE the endpoint answers {"current": v, "latest": v} without any call.
  _ow_api GET /api/version/updates
  if [[ "$OW_CODE" == 200 ]] && [[ "$(_ow_json "$OW_BODY" 'd.get("current") == d.get("latest") and bool(d.get("current"))')" == True ]]; then
    log "update check short-circuited offline: $OW_BODY"
  else
    warn "GET /api/version/updates answered HTTP $OW_CODE: ${OW_BODY:0:120} (expected current == latest; V12 below is the real proof)"
  fi
}

step_03() {
  [[ -n "${OPENWEBUI_PORT:-}" && -n "${ORCH_PORT:-}" ]] || die "OPENWEBUI_PORT/ORCH_PORT are empty (load_env)"
  [[ -s "$CORE_ENV" ]] || die "$CORE_ENV missing: step 02 must run first"
  _ow_secrets
  _ow_up
  _ow_admin_token
  _ow_models
  _ow_filter
  _ow_retention_contract
  _ow_update_check_shortcircuit
  run_verify V12 v12-openwebui-offline.sh "$OW_CONTAINER" 120 \
    || warn "V12 recorded as fail: Open WebUI opened a connection beyond loopback after hardening; the Phase 2 gate will block until it is zero (see the verify table and 'journalctl -k | grep \"ATLAS v12\"')"
  OW_TOKEN=""
  local email
  email="$(awk -F= '$1=="OPENWEBUI_ADMIN_EMAIL" {print $2; exit}' "$OW_PRINCIPAL")"
  cat <<MSG

  ==== Open WebUI is up ====
  URL (LAN):        http://${LAN_IP:-<LAN IP>}:$OPENWEBUI_PORT      (also over WireGuard; refused elsewhere by ufw)
  Login:            $email
  Password:         sudo cat $OW_PRINCIPAL
  Models:           A.T.L.A.S. (default), Ren, Arthur — served by the orchestrator; the router Filter is active.
  Offline:          every update/community/web-search/model-download path is off (Section 12.1); V12 recorded;
                    the egress fence ($OW_EGRESS_UNIT) drops anything else for good.
  Install as app:   NOT available over plain http (browsers need https for "install"; Section 12.1's PWA sentence).
                    Day 1 delivers browser-tab access over LAN/WireGuard. Principal's decision: accept that, or add a
                    TLS front (e.g. caddy on 443 with a self-signed certificate on phone and laptop; firewall change).
  ==========================
MSG
  notify "Phase 2 step 3 done: Open WebUI on http://${LAN_IP:-?}:$OPENWEBUI_PORT (admin $email)"
  log "step 03 done"
}
