"""Governance code paths (Sections 6.4, 16.1 rules 4-6; Appendix A "never-delegate rewrite pass; register set").

No live service: every function under test is deterministic text handling.
"""

from __future__ import annotations

import pytest

from atlas.governance import (
    AUDIENCES,
    DECISION_PREFIX,
    Register,
    disclosure_check,
    never_delegate_rewrite,
    register,
)

# --- never-delegate (16.1 rule 5) --------------------------------------------------------------------------------


def test_task_shaped_request_becomes_decision_request() -> None:
    result = never_delegate_rewrite("Please gather the invoices and send them to me.")
    assert result.changed
    assert result.text.startswith(DECISION_PREFIX)
    assert "shall ATLAS gather the invoices and send them to you?" in result.text
    assert "please gather" not in result.text.lower()
    assert result.rewrites and result.rewrites[0][0].startswith("Please gather")
    assert result.clean  # rewritten, nothing left to flag


@pytest.mark.parametrize(
    "line",
    [
        "Can you find the Q3 bank statements?",
        "Could you please forward the lease to the accountant?",
        "You will need to collect the parcel from the depot.",
        "You'll need to upload the scans to the shared drive.",
        "I need you to chase the supplier for the credit note.",
        "Kindly send me the signed copy.",
        "Don't forget to book the courier.",
    ],
)
def test_rule_list_imperatives_are_rewritten(line: str) -> None:
    result = never_delegate_rewrite(line)
    assert result.changed, line
    assert result.text.startswith(DECISION_PREFIX), result.text
    assert result.text.endswith("?")


@pytest.mark.parametrize(
    "line",
    [
        "Please confirm the meeting time.",
        "Please approve the draft below.",
        "Can you decide between the two venues?",
        "Please find attached the revised proposal.",
        "Let me know which option you prefer.",
        "Decision needed: shall ATLAS renew the domain for two years?",
    ],
)
def test_decision_and_approval_requests_are_left_alone(line: str) -> None:
    result = never_delegate_rewrite(line)
    assert not result.changed, result.text
    assert result.clean


def test_fallback_flags_rather_than_mangles() -> None:
    line = "Let me know when you have gathered the receipts from the accountant."
    result = never_delegate_rewrite(line)
    assert result.text == line  # untouched
    assert result.flagged == (line,)
    assert not result.clean


def test_layout_and_other_sentences_survive() -> None:
    text = (
        "Summary of the week.\n"
        "- Please send me the updated cap table.\n"
        "- The lease renews on 1 October.\n"
        "Send the photos over to me once you are back."
    )
    result = never_delegate_rewrite(text)
    lines = result.text.splitlines()
    assert lines[0] == "Summary of the week."
    assert lines[1].startswith("- Decision needed: shall ATLAS send you the updated cap table?")
    assert lines[2] == "- The lease renews on 1 October."
    assert lines[3] == "Send the photos over to me once you are back."  # flagged, not rewritten (class 2)
    assert result.flagged == ("Send the photos over to me once you are back.",)


def test_pronouns_swap_only_where_needed() -> None:
    result = never_delegate_rewrite("Please email the itinerary to me and my assistant.")
    assert "to you and your assistant" in result.text


def test_empty_text_is_a_no_op() -> None:
    assert never_delegate_rewrite("").text == ""
    assert never_delegate_rewrite("   \n").changed is False


# --- disclosure (16.1 rule 4) ------------------------------------------------------------------------------------


@pytest.mark.parametrize(
    "text",
    [
        "As an AI, I cannot attend in person.",
        "As an AI assistant I have drafted the reply below.",
        "I'm an AI language model and do not hold opinions.",
        "I am not a human, so please bear with me.",
        "This reply was generated by an AI.",
        "Note: my training data ends in 2024.",
        "Our virtual assistant will follow up.",
        "Regards, the chatbot",
        "This was drafted on gpt-oss-120b.",
    ],
)
def test_disclosure_check_flags_admissions(text: str) -> None:
    result = disclosure_check(text)
    assert result.disclosed, text
    assert not result.clean


@pytest.mark.parametrize(
    "text",
    [
        "Thank you for your email; I will revert with the figures on Monday.",
        "The AI Engineer role we discussed closes on Friday.",
        "Please see the attached invoice for the site works.",
        "Gideon Vance\nGeneral Counsel",
    ],
)
def test_disclosure_check_passes_ordinary_correspondence(text: str) -> None:
    assert disclosure_check(text).clean, text


def test_disclosure_hits_are_reported_once_each() -> None:
    result = disclosure_check("As an AI I try; as an AI I fail.")
    assert [h.lower() for h in result.hits].count("as an ai") == 1


# --- register (6.4) ------------------------------------------------------------------------------------------------


def test_register_is_a_property_of_the_draft() -> None:
    assert register("Sorted.", "principal").register is Register.PRINCIPAL
    assert register("Dear Ms Frost,", "external").register is Register.EXTERNAL
    assert register("Result: ok. Action: none.", "director").register is Register.INTERNAL
    assert register("x", "lead").register is Register.INTERNAL
    draft = register("Dear Ms Frost,", "External")
    assert draft.is_external and draft.audience == "external" and draft.text == "Dear Ms Frost,"


def test_unknown_audience_fails_loudly() -> None:
    with pytest.raises(ValueError, match="unknown audience"):
        register("x", "everyone")
    assert set(AUDIENCES) >= {"principal", "external", "internal", "director"}
